stages:
  - build

build:
  stage: build
  image: ubuntu:latest
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq rustup clang llvm libbpf-dev make libelf-dev pkg-config build-essential
    - rustup default stable
  script:
    - cargo build
    - cargo test --lib
  allow_failure: true
