variables:
  HTTP_PROXY: "http://127.0.0.1:7897"
  HTTPS_PROXY: "http://127.0.0.1:7897"
  NO_PROXY: "localhost,127.0.0.1"


stages:
  - build
  - test

build:
  stage: build
  image: rust:latest
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq clang llvm libbpf-dev make libelf-dev pkg-config build-essential 
  script:
    - cargo build
  artifacts:
    paths:
      - target/debug/
    expire_in: 1 hour
  allow_failure: true

test:
  stage: test
  tags:
    - privileged 
  image: rust:latest
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq sudo clang llvm libbpf-dev make libelf-dev pkg-config build-essential

    # Setup eBPF environment
    - mount -t debugfs debugfs /sys/kernel/debug
    - mount -t bpf bpf /sys/fs/bpf
  script:
    - ps aux
    - cargo test -- --skip test_trace_self_memory_operations
  dependencies:
    - build
  allow_failure: true
