stages:
  - build
  - test

build:
  stage: build
  image: rust:latest
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq clang llvm libbpf-dev make libelf-dev pkg-config build-essential 
  script:
    - cargo build
  artifacts:
    paths:
      - target/debug/
    expire_in: 1 hour

test:
  stage: test
  tags:
    - privileged 
  image: rust:latest
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq sudo clang llvm libbpf-dev make libelf-dev pkg-config build-essential

    # Setup eBPF environment
    - mount -t debugfs debugfs /sys/kernel/debug
    - mount -t bpf bpf /sys/fs/bpf
  script:
    - ps aux
    - cargo test --verbose
  dependencies:
    - build
  allow_failure: true